### ISSUE TITLE
How to understand formula 23

### ISSUE THREAD

**Issue by PengKunPROO** [hku-mars/r2live#72]
Hi, I'm new to studying slam and its related knowledge, so I'm confused about how to derive the CP_s as below. Why does it need to minus the Ip_C_{k+1} and the Gp_I_{k+1}? Sincerely waiting for your reply, Thanks!
![image](https://user-images.githubusercontent.com/42089076/203485894-779aa871-f1dc-4308-abb8-efa51ea6206b.png)

**Comment by WFram** [comment]
It's just point (Ps) projection from global to camera frame. But to make it explicitly dependent on the state vector elements (see IV-C in the R2LIVE paper), corresponding elements (IMU -> Global and Camera -> IMU transformations) should be inverted. That's why rotation matrices should be transposed and translation vectors get negative signs in this derivation.

**Comment by PengKunPROO** [comment]
> 

Thank you！ I misunderstand p_C_{k+1} as the corner point's coordinate, so I'm confused about why R_C{k+1} can project the p_C_{k+1} from the camera frame to the IMU frame at the beginning. Thank you for your reply again!
